### ISSUE TITLE
JavaScript error when clicking "Register a Tablet or Computer for Sport Poomsae".

### ISSUE THREAD

**Issue by wcardenas** [mikewongtkd/freescoretkd#4]
Hello,

I have installed FreeScore v4.0 beta on a RPI3 and believe I have everything configured correctly however when I click the "Register a Tablet or Computer for Sport Poomsae" link on the main page the following error is generated in Chromium and Chrome:

Uncaught TypeError: Cannot read property 'length' of null
    at e.(anonymous function).(anonymous function)._create (http://freescore.net/freescore/include/js/forms/worldclass/jquery.register.js:306:32)
    at e.(anonymous function).(anonymous function)._create (http://freescore.net/freescore/include/jquery/js/jquery-ui.min.js:6:5029)
    at e.(anonymous function).(anonymous function)._createWidget (http://freescore.net/freescore/include/jquery/js/jquery-ui.min.js:6:7033)
    at new e.(anonymous function).(anonymous function) (http://freescore.net/freescore/include/jquery/js/jquery-ui.min.js:6:4592)
    at HTMLDivElement.<anonymous> (http://freescore.net/freescore/include/jquery/js/jquery-ui.min.js:6:6306)
    at Function.each (http://freescore.net/freescore/include/jquery/js/jquery.js:648:23)
    at init.each (http://freescore.net/freescore/include/jquery/js/jquery.js:270:17)
    at init.e.fn.(anonymous function) [as register] (http://freescore.net/freescore/include/jquery/js/jquery-ui.min.js:6:6229)
    at http://freescore.net/freescore/forms/worldclass/register.php:20:16

On Firefox I get:

TypeError: tournament.rings is null

Not sure what direction to take at this point. The Chrom(e)(ium) error seems to be related to the error generated by Firefox where tournament.rings is null. I copied the test data which has rings and I can see the rings when I click "Manage Sport Poomsae Divisions".

Thanks for any help you can provide.

**Comment by wcardenas** [comment]
Resolved the issue. I only copied the worldclass data files and the config.php script on the backend was expecting both grassroots and worldclass and crashed. I copied the grassroots data also and it works now. Sorry for the false alarm. :-)
